export const name = 'BusData'

export const BUS_ROUTES_LIST_API_URL = 'https://svc.metrotransit.org/nextripv2/routes'
export const BUS_ROUTE_DIRECTION_BASE_API_URL = 'https://svc.metrotransit.org/nextripv2/directions/'
export const BUS_ROUTE_STOPS_BASE_API_URL = 'https://svc.metrotransit.org/nextripv2/stops/'
export const BUS_STOP_DEPARTURE_BASE_API_URL = 'https://svc.metrotransit.org/nextripv2/'
export const ROUTE_INFORMATION_URL = 'https://svc.metrotransittest.org/schedule/routes'

export const ACTIONS_SET_ROUTE_ID = 'SET_ROUTE_ID'
export const ACTIONS_SET_ROUTE_DIRECTIONS = 'SET_ROUTE_DIRECTIONS'
export const ACTIONS_SET_ROUTE_STOPS = 'SET_ROUTE_STOPS'
export const ACTIONS_SET_DEPARTURES = 'SET_DEPARTURES'
export const ACTIONS_SET_DIRECTION = 'SET_DIRECTION'
export const ACTIONS_SET_STOP = 'SET_STOP'

export const ROUTE_NOT_FOUND_STRING = 'Route not found'
export const PLEASE_SELECT_ROUTE_STRING = 'Please select a route'
export const ROUTE_SELECTED_STRING = 'Route Selected'
export const SELECTED_STOP_STRING = 'Selected Stop'
export const NEXT_DEPARTURES_STRING = 'Next Departures'
export const DIRECTION_STRING = 'Direction'
export const TITLE_STRING = 'Metro Transit Exercise'
export const FILTER_ROUTES_STRING = 'Filter Routes'